Bug 1916007: olm skip range is set to the wrong range
openshift/cluster-nfd-operator pull request #127
Opened 2021-01-19 01:37 UTC by zerodayz

my understanding is this wouldn't upgrade to 4.1.0-> to 4.7.0,
meaning it would miss upgrade in 4.6.z

We saw same issue https://github.com/openshift/cluster-nfd-operator/pull/124/files
and the issue comes from mis-understanding of olm.skipRange.

2021-01-19 02:15 UTC, ArangoGutierrez approved these changes
Thanks for this!!!! Really appreciated
/lgtm

2021-01-19 02:16 UTC, ArangoGutierrez commented
/approve

2021-01-19 02:17 UTC, ArangoGutierrez commented
/assign

2021-01-19 09:47 UTC, zerodayz commented
/test e2e-aws

2021-01-26 01:50 UTC, ArangoGutierrez approved these changes
/lgtm

2021-01-27 13:31 UTC, ArangoGutierrez requested changes

2021-01-27 13:31 UTC, ArangoGutierrez commented on manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml
> +    olm.skipRange: ">=4.1.0 <4.6.0"
```suggestion
    olm.skipRange: ">=4.3.0 <4.6.0"
```

2021-01-27 13:32 UTC, ArangoGutierrez commented on manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml
> +    olm.skipRange: ">=4.1.0 <4.6.0"
PING @zerodayz

2021-01-27 21:52 UTC, zerodayz commented on manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml
> +    olm.skipRange: ">=4.1.0 <4.6.0"
@ArangoGutierrez PONG

2021-01-27 21:56 UTC, ArangoGutierrez approved these changes
Awesome @zerodayz 
/lgtm

2021-02-02 21:12 UTC, zvonkok commented
/approved

2021-02-03 22:59 UTC, zerodayz commented
@zvonkok Hi! It seems there was a typo in `/approved`, as per https://prow.k8s.io/command-help#approve it should be `/approve`. Would you mind please approving again? Thank you!

2021-02-03 23:00 UTC, ArangoGutierrez commented
/approve

2021-02-03 23:00 UTC, ArangoGutierrez approved these changes
/approve

2021-02-03 23:00 UTC, ArangoGutierrez commented
> @zvonkok Hi! It seems there was a typo in `/approved`, as per https://prow.k8s.io/command-help#approve it should be `/approve`. Would you mind please approving again? Thank you!

approve has been given, now we need to wait for the patch manager

2021-02-03 23:01 UTC, ArangoGutierrez commented
@zvonkok I am not an approver for 4.6, just 4.7+ , so you need to approve this one

2021-02-03 23:04 UTC, zvonkok commented
/approve now! :)

2021-02-06 20:31 UTC, zerodayz commented
@ArangoGutierrez Can you give label cherry-pick-approved, seems that one is still missing. Thank you!

2021-02-06 20:37 UTC, ArangoGutierrez commented
I can't, it needs to be the patch manager

2021-02-24 21:26 UTC, ArangoGutierrez commented
@zvonkok could we PING the patch manager, it's been almost 20 days since this Patch is ready

2021-02-24 21:37 UTC, ArangoGutierrez commented
/bugzilla refresh

2021-02-24 21:43 UTC, ArangoGutierrez commented
Hey! thanks @mrunalp !!

2021-02-24 22:28 UTC, zerodayz commented
Thank you guys @ArangoGutierrez @mrunalp @zvonkok for keeping this rolling.

2021-02-24 23:11 UTC, ArangoGutierrez commented
/test e2e-aws

2021-02-25 00:36 UTC, merged