Adding documentation for the health check flag in 'main.go'
openshift/cluster-nfd-operator pull request #167
Opened 2021-05-12 23:45 UTC by courtneypacheco

The documentation for the 'health check' flag is nonexistent. This commit aims to describe to contributors what this flag does understand how it works.

2021-05-13 05:01 UTC, courtneypacheco commented
/cc @ArangoGutierrez

2021-05-13 16:15 UTC, ArangoGutierrez requested changes
> Upstream

2021-05-13 16:15 UTC, ArangoGutierrez commented on main.go
> +        // of the NFD containers. Note that the port which is being binded must match
```suggestion
        // of the operator pods. Note that the port which is being binded must match
```

2021-05-13 20:02 UTC, ArangoGutierrez commented
Not urgent PR, will unhold after code freeze

/hold

2021-06-14 14:43 UTC, ArangoGutierrez commented
/hold cancel
/retest

2021-06-14 14:44 UTC, ArangoGutierrez commented
/hold cancel

2021-06-14 14:44 UTC, ArangoGutierrez commented
/retest

2021-06-14 16:19 UTC, ArangoGutierrez approved these changes
/lgtm

2021-06-15 06:33 UTC, jmencak requested changes

2021-06-15 06:33 UTC, jmencak commented on main.go
> +        // the bind port under './config' and './manifests'
- Mixing spaces (here) with tabs (code), please use them consistently.
- s/and './manifests'/and './manifests'./  ?
-

2021-06-15 06:37 UTC, jmencak commented
/shrug

2021-06-19 05:59 UTC, merged