Replace all non-klog logging lines with klog
openshift/cluster-nfd-operator pull request #203
Opened 2021-08-16 19:07 UTC by courtneypacheco

The operator code is inconsistent in terms of the types of logging methods used. Prior to this commit, logr, logf, etc. were being
used in addition to klog. To keep things consistent, I have removed all non-klog logging statements and replaced them with klog logging statements.

2021-08-17 11:36 UTC, courtneypacheco commented
/retest-required

2021-08-17 11:38 UTC, courtneypacheco commented
/assign @ArangoGutierrez

2021-08-17 12:44 UTC, courtneypacheco commented
/retest-required

2021-08-17 17:31 UTC, ArangoGutierrez approved these changes
waiting on the extra feature we discussed offline, but looks good so far , thanks for this

2021-08-17 18:17 UTC, courtneypacheco commented
/retest-required

2021-08-17 19:50 UTC, courtneypacheco commented
/retest-required

2021-08-17 20:00 UTC, courtneypacheco commented
/retest-required

2021-08-17 20:05 UTC, courtneypacheco commented
/retest-required

2021-08-17 20:17 UTC, ArangoGutierrez commented
after this PR, TODO should be klog/v2

2021-08-19 19:34 UTC, ArangoGutierrez requested changes

2021-08-19 19:34 UTC, ArangoGutierrez commented on go.mod
> +	k8s.io/klog/v2 v2.4.0
Can it be 2.9 as NFD https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/go.mod#L20

2021-08-23 17:39 UTC, courtneypacheco commented
@ArangoGutierrez I changed the klog version to v2.9.0 as requested. PTAL.

2021-08-24 13:19 UTC, ArangoGutierrez commented
Testing this one today

2021-08-25 00:37 UTC, ArangoGutierrez approved these changes
looks good, will merge once we push this to upstream first

2021-08-31 17:58 UTC, ArangoGutierrez commented
Rebase after https://github.com/openshift/cluster-nfd-operator/pull/184 merge

2021-09-01 15:32 UTC, ArangoGutierrez approved these changes
/lgtm

2021-09-01 16:54 UTC, merged